artifacts_root: "artifacts"

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_url: https://github.com/Pyro137/ML-Project-End-to-End/raw/main/WineQT.zip
  local_data_file: artifacts/data_ingestion/WineQT.zip
  unzip_dir: artifacts/data_ingestion
